[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/keystatic"
  to = "/.netlify/functions/entry"
  status = 200

[[redirects]]
  from = "/keystatic/*"
  to = "/.netlify/functions/entry"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = ".netlify/functions/"
  node_bundler = "esbuild"
