[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/keystatic"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[[redirects]]
  from = "/keystatic/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[[redirects]]
  from = "/api/keystatic/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[functions]
  directory = ".netlify/functions/"
  node_bundler = "esbuild"

[build.environment]
  ASTRO_ADAPTER = "netlify"
